### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by chriscamacho** [ScrelliCopter/qmap#1]
The code is copyrighted, but there is no license included in the repo, as such I can't use it in an open source (or even proprietary) project...

**Comment by ScrelliCopter** [comment]
Hello, REDIST.TXT in qmsrc.zip places Sean's code into the public domain. (prehaps I shouldn't have removed that file when I added the original code as a zip)
I'm perfectly happy with placing my alterations into the public domain in the spirit of the original project, so go ahead and use them as you please.
If you absolutely need a license though I suppose I can drop CC0 or something into the repo.

**Comment by chriscamacho** [comment]
you might as well protect yourself from sue balls...
